### ISSUE TITLE
GPU Memory needed

### ISSUE THREAD

**Issue by dakshvar22** [Bartzi/see#1]
Hi,

How much minimum GPU memory is required to train the network? I have one GTX 1080 ti(11 gb). Would it be enough?

Thanks

**Comment by Bartzi** [comment]
Hi,
sry for my late reply, I just did not see your Issue :sweat_smile:...
This GPU will definetly be enough. Our experiments usually used not more than 8 GB of memory

**Comment by novioleo** [comment]
distribute train would be the best.
