### ISSUE TITLE
where does the training params store?

### ISSUE THREAD

**Issue by qnkhuat** [Bartzi/see#12]
Hi,
I wonder where new params store.
and how can I use it for demo ?

**Comment by Bartzi** [comment]
trained params are stored in the `*.npz` files that are produced by the snapshotter (after each epoch, or after a given amount of iterations. This amount of iterations os configured with the `--snapshot-interval` command line switch). I also provided some of those files on [bartzi.de](https://bartzi.de/research/see).

The [README](https://github.com/Bartzi/see#text-recognition-demo) also tells you how to use those models.

**Comment by qnkhuat** [comment]
oh. I see. Thank u :D

**Comment by qnkhuat** [comment]
oh. So it is the model which I specified in training command. In my case I use model_190000.npz?

**Comment by Bartzi** [comment]
If you want to to use the demo script on one of my models you should use `model_190000.npz` but if you want to use a model trained on your dataset, you will have to use one generated by the training. You can find it in the log folder that has been created for your train run.

Is that what you want to know? I'm not sure whether I get your question.

**Comment by qnkhuat** [comment]
yes. I want to use the model I trained

**Comment by Bartzi** [comment]
okay, you should find a model in the log folder. Look for any `.npz` files if there is nothing there yet, you'll have to wait or set the `--snapshot-interval` command line switch
