### ISSUE TITLE
Explanation of "ctc_char_map.json"

### ISSUE THREAD

**Issue by gengkunling** [Bartzi/see#14]
In the file "ctc_char_map.json", I saw a dictionary like this in below, could you explain what is means?

Another questions is how many characters does the current text recognition model supports? Is it only supports ascii characters? Thanks!

{"0": 9250,
    "1": 48,
    "2": 49,
    "3": 50,
    "4": 51,
    "5": 52,
    "6": 53,
    "7": 54,
    "8": 55,
    "9": 56,
    "10": 57,
    "11": 97,
    "12": 98,
    "13": 99,
...
}

**Comment by rohit12** [comment]
You can reference the last comment in this  #6[issue]

**Comment by gengkunling** [comment]
Thanks! It's very clear now.

**Comment by Bartzi** [comment]
@rohit12 thanks for your help =)
