### ISSUE TITLE
Error while trying to train on the SVHN dataset

### ISSUE THREAD

**Issue by rohit12** [Bartzi/see#7]
Hi Christian, 

I wanted to open a new issue for this since I wasn't sure whether it is related to the dataset or not. 

I downloaded the dataset that you linked to in #6 and tried to train my model from scratch using that data. 

The command for that was: `python3 chainer/train_svhn.py data/curriculum.json logs/ -b 32`
The `curriculum.json` file indicates the paths to the "train.csv" and "valid.csv". 

I get the following error:

Traceback (most recent call last):
  File "chainer/train_svhn.py", line 76, in <module>
    train_dataset, validation_dataset = curriculum.load_dataset(0)
  File "/home/rohit_shinde12194/see/chainer/utils/baby_step_curriculum.py", line 38, in load_dataset
    train_dataset = self.dataset_class(self.train_curriculum[level], **self.dataset_args)
  File "/home/rohit_shinde12194/see/chainer/datasets/file_dataset.py", line 31, in __init__
    self.num_timesteps, self.num_labels = (int(i) for i in next(reader))
  File "/home/rohit_shinde12194/see/chainer/datasets/file_dataset.py", line 31, in <genexpr>
    self.num_timesteps, self.num_labels = (int(i) for i in next(reader))
ValueError: invalid literal for int() with base 10: 'train/0.png'

I am clearly doing something wrong. Could you help me out with this?

Thanks again!

**Comment by Bartzi** [comment]
You get this error because you did not add the mentioned metadata, that encodes the number of timesteps the localization network and recognition network should run.
See your other issue. I tried to explain this there.

**Comment by harshalcse** [comment]
@Bartzi @rohit12  how you can resolve this issue because I also get same error but never recollect above reply for given issue.
