### ISSUE TITLE
fsns_demo error on configuration

### ISSUE THREAD

**Issue by Jeffyangchina** [Bartzi/see#73]
Dear host,
When i run the fsns_demo.py, it occurred  importError: from chainer import configuration.
I couldn't find the "configuration", is it removed?

**Comment by Bartzi** [comment]
Did you checkt hat you are using the correct version of chainer, as indicated in the file `requirements.txt`?

**Comment by Jeffyangchina** [comment]
Thank you for your answer,because i didn't install from requirements.txt so  i didn't notice the chainer is a python lib, i just saw the same name folder.

**Comment by Bartzi** [comment]
Yeah, I'm sorry if my naming convention confused you :sweat_smile:
