### ISSUE TITLE
svhn demo

### ISSUE THREAD

**Issue by keekeecaca** [Bartzi/see#75]
I have a trained SVHN with my custom dataset, any svhn_demo.py or guidance for svhn inference? thanks.

**Comment by Bartzi** [comment]
Hmm, in the end it should not be that different from the other two demo files. You just need to load the model and initialize the weights of the chain with the trained model. Then you'll have to load an image and convert it the same way, you converted your training images.
After you've done that you just call the chain and do a forward pass with your input image. You will get the bounding box information and the predeicted characters, and then you can do whatever you like with those.

So just have a look at the other two demo scripts. You should not need many adjustments.

**Comment by ahmed-nady** [comment]
@Bartzi Thanks for sharing your code.  After I created a svhn_demo.py as mentioned above. I encountered an issue related to pre-trained models. So, Where Can i find the SVHN model for your 3 experiments or should I train in order to obtain them?

**Comment by Bartzi** [comment]
Currently, we did not publish the SVHN models. I'm actually not sure whether I can find them again :sweat_smile: it has been quite some time since we did the last experiments.
So, your best option is to run the training for each of the models again.
