### ISSUE TITLE
Training on right to left datasets

### ISSUE THREAD

**Issue by Mr-DDDAlKilanny** [Bartzi/see#78]
As you mentioned you trained your network assuming left-to-right ordering. How can I modify it to be right to left?

**Comment by Bartzi** [comment]
The assumption is based on the ordering of the words in the groundtruth. It can easily be modified to be right to left, by reordering the words in the groundtruth. If you want to reorder the characters, you'll also just have to change the order in the gt. 
The only thing you have to keep in mind, is that you have a consistent order in your groundtruth. Apart from that it doesn't matter if it is left to right or right to left.

**Comment by Mr-DDDAlKilanny** [comment]
So I should change words ordering only, but characters I can keep right to left in words, right? The style of this language is cursive (connected characters), so no problem as I understand.

**Comment by Bartzi** [comment]
Exactly, there is no need to change the characters, only the ordering of the words in your groundtruth file.
The style of the characters should be no problem.
