### ISSUE TITLE
I get a problem on train_text_recognition.py

### ISSUE THREAD

**Issue by ghost** [Bartzi/see#79]
HI
when i run:

sudo python3 chainer/train_text_recognition.py dataset_specification   text_rec55ognition_model/small_dataset/curriculum.json log_dir log   -b 2 --char-map text_recognition_model/small_dataset/ctc_char_map.json 

I get some error:

train_text_recognition.py: error: unrecognized arguments: log_dir log

please help,thanks!

**Comment by ghost** [comment]
log    Is a newly created folder

**Comment by Bartzi** [comment]
please try this:

` python3 chainer/train_text_recognition.py dataset_specification text_rec55ognition_model/small_dataset/curriculum.json log -b 2 --char-map text_recognition_model/small_dataset/ctc_char_map.json`

**Comment by yufeilongyuan** [comment]
> please try this:
> 
> ` python3 chainer/train_text_recognition.py dataset_specification text_rec55ognition_model/small_dataset/curriculum.json log -b 2 --char-map text_recognition_model/small_dataset/ctc_char_map.json`

**Comment by ghost** [comment]
python3 chainer/train_text_recognition.py dataset_specification text_recognition_model/small_dataset/curriculum.json log -b 2 --char-map text_recognition_model/small_dataset/ctc_char_map.json


I run ,same error,please help?Is it related to the configuration environment?

**Comment by Bartzi** [comment]
I'm sorry, please try this:

`python3 chainer/train_text_recognition.py text_rec55ognition_model/small_dataset/curriculum.json log -b 2 --char-map text_recognition_model/small_dataset/ctc_char_map.json`

**Comment by ghost** [comment]
Where can I find ”text_rec55ognition_model“?text_recognition_model.zip Can't find
