### ISSUE TITLE
This site can't be reached - when trying to download pretrained models in bartzi.de/research/see

### ISSUE THREAD

**Issue by jdgalviss** [Bartzi/see#90]
First of all thanks for this amazing contribution. I am trying to download the pretrained models from bartzi.de/research/see. However the server seems to be down on unreachable. Is this something temporary? Thanks

**Comment by Bartzi** [comment]
Thanks for bringing this to my attention. It should work now!

**Comment by jdgalviss** [comment]
Working perfectly! Thanks a lot!
