### ISSUE TITLE
Question about recognizing digits

### ISSUE THREAD

**Issue by anavc94** [Bartzi/see#95]
Hello,

first of all, I am sorry for opeaning an issue as actually I just want to ask your opinion. Your library has helped me a lot, it is the one that gives me decent results (over tesseract, etc.). 

I am testing how the "Text Recognition" part works when trying to get the words from images of the following type:  

![codigo_362](https://user-images.githubusercontent.com/37656547/80703319-d6d8dd00-8ae2-11ea-9e6a-9413eea8048c.JPEG)

Specially, I want to get the digits. If I crop single digits and pass over the demo script, transcriptions are pretty good. I set the timesteps as 1 and the num_labels as 1 as well. However, I would prefer to pass the entire image, which is always going to contain 1 text area with 11 digits in vertical, from 0 to 9. Changing the num_labels to 11 doesn't work. I would like to ask you for some recommendations. Maybe I should fine tuning your model?

Thanks in advance

**Comment by Bartzi** [comment]
Thanks for your question, glad to hear that our code helps you!

For your kind of images I can give the following advice:
- your images have a different aspect ratio than the data we used to train our model on, so you will need to at least retrain the localization model and make sure that data loading and resizing does not destroy the images
- Furthermore, I suggest that you use our newer version, which is made for text recognition only: [here](https://github.com/Bartzi/kiss), it uses a similar architecture but has a much improved recognition part. And might also be easier to train, I think. You'll still have to retrain the localization part of the network and make sure that input images are resized differently.

I hope this helps!

**Comment by anavc94** [comment]
Hi @Bartzi ,

thank you so much for your advices, I really appreciate them and your kindness. I am gonna try what you said and maybe I'll update with news :) 

I close this issue and again, sorry for posting here. 
Regards!
